### ISSUE TITLE
Does not deposit into Yearn when add liquidity

### ISSUE THREAD

**Issue by apebuilder** [yapeswap/yape-core#1]
Currently, we are using [`_rebalance`](https://github.com/yapeswap/yape-core/blob/main/contracts/core/YapePair.sol#L111-L130) function to manage farming reserves.

But when users add liquidity to pools, the [`mint`](https://github.com/yapeswap/yape-core/blob/main/contracts/uni-v2/UniswapV2Pair.sol#L69-L93) function does not call `_rebalance` function. So newly added liquidity cannot be deposited until someone swaps or burns one's liquidity. 

I think we can fix this by calling `_rebalance` inside of `mint` function. I'll quickly fix this issue soon.

**Comment by 0xMayflower** [comment]
good point, would you create a pr for it?
